# DIABETES CLASSIFICATION USING RANDOM FOREST ALGORITHEM

## IMPORTING LIBRARY

In [1]:
import numpy as np
import pandas as pd

## IMPORTING DATASET

In [2]:
dataset = pd.read_csv('diabetes.csv')

In [3]:
dataset

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0               2      138             62             35        0  33.6   
1               0       84             82             31      125  38.2   
2               0      145              0              0        0  44.2   
3               0      135             68             42      250  42.3   
4               1      139             62             41      480  40.7   
...           ...      ...            ...            ...      ...   ...   
1995            2       75             64             24       55  29.7   
1996            8      179             72             42      130  32.7   
1997            6       85             78              0        0  31.2   
1998            0      129            110             46      130  67.1   
1999            2       81             72             15       76  30.1   

      DiabetesPedigreeFunction  Age  Outcome  
0                        0.127   47        1  
1                        0.233   23        0  
2                        0.630   31        1  
3                        0.365   24        1  
4                        0.536   21        0  
...                        ...  ...      ...  
1995                     0.370   33        0  
1996                     0.719   36        1  
1997                     0.382   42        0  
1998                     0.319   26        1  
1999                     0.547   25        0  

[2000 rows x 9 columns]

## CHECKENING HOW MANY 0 ARE IN DATASET

In [4]:
print((dataset['Glucose']==0).sum())
print((dataset['BloodPressure']==0).sum())
print((dataset['SkinThickness']==0).sum())
print((dataset['Insulin']==0).sum())
print((dataset['BMI']==0).sum())
print((dataset['DiabetesPedigreeFunction']==0).sum())
print((dataset['Age']==0).sum())

13
90
573
956
28
0
0


## FINDING THE MEAN VALUE OF THE COLUMN

In [5]:
print(dataset['Glucose'].mean())
print(dataset['BloodPressure'].mean())
print(dataset['SkinThickness'].mean())
print(dataset['Insulin'].mean())
print(dataset['BMI'].mean())

121.1825
69.1455
20.935
80.254
32.192999999999984


## REPLACING 0 WITH THE MEAN VALUE OF THAT COLUMN

In [6]:
dataset['Glucose'] = dataset['Glucose'].replace(0,121.1825)
dataset['BloodPressure'] = dataset['BloodPressure'].replace(0,69.1455)
dataset['SkinThickness'] = dataset['SkinThickness'].replace(0,20.935)
dataset['Insulin'] = dataset['Insulin'].replace(0,80.254)
dataset['BMI'] = dataset['BMI'].replace(0,32.192999999999984)

In [7]:
dataset

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0               2    138.0        62.0000         35.000   80.254  33.6   
1               0     84.0        82.0000         31.000  125.000  38.2   
2               0    145.0        69.1455         20.935   80.254  44.2   
3               0    135.0        68.0000         42.000  250.000  42.3   
4               1    139.0        62.0000         41.000  480.000  40.7   
...           ...      ...            ...            ...      ...   ...   
1995            2     75.0        64.0000         24.000   55.000  29.7   
1996            8    179.0        72.0000         42.000  130.000  32.7   
1997            6     85.0        78.0000         20.935   80.254  31.2   
1998            0    129.0       110.0000         46.000  130.000  67.1   
1999            2     81.0        72.0000         15.000   76.000  30.1   

      DiabetesPedigreeFunction  Age  Outcome  
0                        0.127   47        1  
1                        0.233   23        0  
2                        0.630   31        1  
3                        0.365   24        1  
4                        0.536   21        0  
...                        ...  ...      ...  
1995                     0.370   33        0  
1996                     0.719   36        1  
1997                     0.382   42        0  
1998                     0.319   26        1  
1999                     0.547   25        0  

[2000 rows x 9 columns]

## LOCATING VARIABLES AND LABLES

In [8]:
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

## DIVIDING DATASET INTO TRANING AND TASTING SETS

In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state =7)

In [10]:
print(X_train)

[[1.300e+01 1.530e+02 8.800e+01 ... 4.060e+01 1.174e+00 3.900e+01]
 [0.000e+00 1.160e+02 6.400e+01 ... 4.020e+01 7.200e-01 5.000e+01]
 [6.000e+00 8.000e+01 8.000e+01 ... 3.980e+01 1.770e-01 2.800e+01]
 ...
 [0.000e+00 5.700e+01 6.000e+01 ... 2.170e+01 7.350e-01 6.700e+01]
 [1.000e+01 1.010e+02 7.600e+01 ... 3.290e+01 1.710e-01 6.300e+01]
 [8.000e+00 1.790e+02 7.200e+01 ... 3.270e+01 7.190e-01 3.600e+01]]


In [11]:
print(X_test)

[[3.00e+00 1.06e+02 7.20e+01 ... 2.58e+01 2.07e-01 2.70e+01]
 [2.00e+00 1.12e+02 7.80e+01 ... 3.94e+01 1.75e-01 2.40e+01]
 [6.00e+00 1.03e+02 7.20e+01 ... 3.77e+01 3.24e-01 5.50e+01]
 ...
 [0.00e+00 1.23e+02 7.20e+01 ... 3.63e+01 2.58e-01 5.20e+01]
 [9.00e+00 5.70e+01 8.00e+01 ... 3.28e+01 9.60e-02 4.10e+01]
 [4.00e+00 1.15e+02 7.20e+01 ... 2.89e+01 3.76e-01 4.60e+01]]


## FEATURE SCALING

In [12]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [13]:
print(X_train)

[[ 2.80878324  1.03081873  1.32205101 ...  1.10546586  2.22681535
   0.52358504]
 [-1.12028944 -0.18134409 -0.68168705 ...  1.05033105  0.80120939
   1.46992672]
 [ 0.69312872 -1.36074575  0.65413832 ...  0.99519623 -0.90386558
  -0.42275664]
 ...
 [-1.12028944 -2.11425237 -1.01564339 ... -1.49965404  0.84831091
   2.93245477]
 [ 1.90207416 -0.67276145  0.32018198 ...  0.04412071 -0.92270619
   2.58833052]
 [ 1.29760144  1.88260882 -0.01377436 ...  0.01655331  0.79806929
   0.26549186]]


In [14]:
print(X_test)

[[-0.21358036 -0.50895566 -0.01377436 ... -0.93452221 -0.80966254
  -0.5087877 ]
 [-0.51581672 -0.31238872  0.48716015 ...  0.94006142 -0.91014578
  -0.76688088]
 [ 0.69312872 -0.60723914 -0.01377436 ...  0.70573847 -0.4422707
   1.90008203]
 ...
 [-1.12028944  0.04798401 -0.01377436 ...  0.51276662 -0.64951738
   1.64198884]
 [ 1.5998378  -2.11425237  0.65413832 ...  0.03033701 -1.15821378
   0.69564716]
 [ 0.088656   -0.21410525 -0.01377436 ... -0.50722741 -0.27898543
   1.12580247]]


## IMPORTING THE ALGORITHEM

In [15]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 5,max_depth=10, criterion = 'entropy', random_state = 10)
classifier.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='entropy', max_depth=10, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=5,
                       n_jobs=None, oob_score=False, random_state=10, verbose=0,
                       warm_start=False)

## COMPARING PRIDICTED RESULT WITH ACTUAL RESULT

In [16]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [0 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 1]
 [0 1]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 0]
 [0 0]

## CREATING CONFUSION MATRIX

In [17]:
from sklearn.metrics import confusion_matrix, accuracy_score,mean_absolute_error
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[321   9]
 [ 24 146]]


0.934

## ANALYSING THE RESULT

In [18]:
#traning accuracy
Yp_train = classifier.predict(X_train)
(Yp_train == y_train).sum()/len(X_train)

0.9586666666666667

In [19]:
#tseting accuracy
Yp_test = classifier.predict(X_test)
(Yp_test == y_test).sum()/len(X_test)

0.934

In [20]:
mean_absolute_error(y_test,y_pred)

0.066